### PR TITLE
Update button style for new brand

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Update button style for new brand
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #https://github.com/PrestaShop/PrestaShop/issues/34900
| Sponsor company   | -
| How to test?      | -

**The new buttons have a new class, to avoid conflicts with those of bootstrap, like on prestashop.com**

### CODE REVIEW

**Review by matks — CHANGES_REQUESTED** [review]
Hello @M0rgan01 nice work on the homepage, however I'm afraid we have unwanted side-effects on other pages.

If you visit `/releases/prestashop81/` you will have a bad display on the buttons at the end of the page

Capture d’écran 2023-12-27 à 22 14 03

**Comment by M0rgan01** [comment]
@matks we need merge https://github.com/PrestaShop/open-source/pull/244 before for new button.

**Review by tleon — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by matks — APPROVED** [review]
Great work 👍

**Comment by matks** [comment]
Thank you @M0rgan01

**Pull request merged**
