### PR TITLE
Remove not needed transitions + capitalization

### PR DESCRIPTION
**Pull request by kpodemski**
Before:

https://user-images.githubusercontent.com/2137763/183080122-0c29d96d-9c25-4297-9563-ae670710b507.mov

After:

https://user-images.githubusercontent.com/2137763/183080150-6f26ac84-ea68-4c71-bada-adf798091e32.mov

### CODE REVIEW

**Review by matks — APPROVED** [review]
Good for me

@eternoendless ?

**Comment by eternoendless** [comment]
That's so weird. I don't get those transitions at all on Chrome 104 nor on Safari 15.5.

**Comment by kpodemski** [comment]
@eternoendless :D "it's working for me"? :D 

@matks do you have this issue or am I the only one with it?

**Comment by kpodemski** [comment]
@eternoendless, I don't see an issue right now after upgrading Chrome. I still think this transition is not needed tho

**Pull request closed without merging**
